### ISSUE TITLE
Decide how to work on this resource

### ISSUE THREAD

**Issue by jonathantneal** [diveintomark/diveintohtml5#23]
Recently we learned that a lot of people think this GitHub project is a memorial to Mark Pilgrim, and they treat it with a kind of reverence as though our touching it were removing his dead body from a casket.

It's sad because the man isn't even dead either.  That's my opinion, at least.  Mark put it on GitHub at one point so we could fork it.  This was Mark Pilgrim's Disneyland, and I think it works in the same way as Walt put it:

> Disneyland will never be completed. It will continue to grow as long as there is imagination left in the world.

However, as a canonical resource, we have to decide how we're going to treat this gift we have been left with.  What is okay to edit in this living document?  Is it a living document?  Should we revert other changes?  Do we update sections that are wrong or outdated? Do we stick to changing pure numbers, dates, and "easy" things? Would we ever change the layout to fit on a tablet?

These and others are the questions I'd like us to answer.

We can't leave this to a mob consensus in the future.  Earlier today someone asserted something to me as though Mark were a deity: "When Mark said 'with contributions from the community' he didn't mean for you to put words into his mouth" ... though, ironically for both of us, the truth is that "with contributions from the community" are my words.

**Comment by ghost** [comment]
> There could also be [contributing file](https://github.com/blog/1184-contributing-guidelines).

Before there can be a contributing file I'd say the project should either be cross-linked or merged with the fork from @jonathantneal. I see commits from Irish in here so I'm going to suggest @jonathantneal subs a pull with one commit per section and we all take a stab at reviewing then address the URL issue I just opened with #92. This is a great resource – I'm happy to help review.

**Comment by paulirish** [comment]
@jhabdas afaik this repo is up to date with jonathan's fork. 

closing this issue as the repo is in a state of low-maintenance.
