### ISSUE TITLE
Generic Headers using hgroup deprecated

### ISSUE THREAD

**Issue by tchalvak** [diveintomark/diveintohtml5#69]
This page:  http://diveintohtml5.info/semantics.html#header-element

gets into explaining the need to make headers generic, but it relies on the hgroup element to explain how that would work, which is now deprecated:
http://www.w3.org/html/wg/drafts/html/master/common-idioms.html#sub-head

Now, the current recommendation is effectively to use: 
<pre>
    &lt;header&gt;&lt;h1&gt;main-title&lt;/h1&gt;&lt;p&gt;sub-heading&lt;/p&gt;&lt;/header&gt;
</pre>
Or some variation thereof, simple and sweet.
http://www.w3.org/html/wg/drafts/html/master/common-idioms.html#sub-head

I could make a pull request with simplification & changes if that's the appropriate approach for this repository.

**Comment by tchalvak** [comment]
Err, PR is exists https://github.com/diveintomark/diveintohtml5/pull/75
Let me know if anything isn't up to code. *bu-dun-ptch*

**Comment by paulirish** [comment]
closed by #75 
thanks!
