### ISSUE TITLE
old link broken

### ISSUE THREAD

**Issue by kweztah** [diveintomark/diveintohtml5#79]
On page http://diveintohtml5.info/semantics.html:

<a href="http://mxr.mozilla.org/mozilla-central/source/parser/htmlparser/src/nsElementTable.cpp">nsElementTable.cpp</a>

Seems Mozilla moved stuff around, source now here:

http://mxr.mozilla.org/mozilla-central/source/parser/htmlparser/nsElementTable.cpp

**Comment by kweztah** [comment]
Note: the link checker run for pull request #80 did not pick this up, so it wasn't edited (my bad, my memory sucks)...

**Comment by paulirish** [comment]
;) fixed

amusingly it moved again since your comment.
