### ISSUE TITLE
Domain name DIVEINTOHTML5.INFO expired

### ISSUE THREAD

**Issue by vennieso** [diveintomark/diveintohtml5#83]
Whois record:

>Domain Name:DIVEINTOHTML5.INFO
>Domain ID: D42815552-LRMS
>Creation Date: 2011-10-05T03:34:16Z
>Updated Date: 2015-10-04T10:55:02Z
>Registry Expiry Date: **2015-10-05T03:34:16Z**

**Comment by vennieso** [comment]
Domain renewed

**Comment by jonathantneal** [comment]
Whew. I was scared for a minute there.

**Comment by paulirish** [comment]
@VennieSo do you still own this domain? how about i take it over?

**Comment by jonathantneal** [comment]
I’ve owned the domain, @paulirish. Some of my sites were hijacked by an ad bot last year, and I never caught notice that this site was affected. I’ve fixed it.
