### ISSUE TITLE
Website looks broken

### ISSUE THREAD

**Issue by harikt** [diveintomark/diveintohtml5#88]
Hi, 

All links in the website shows only one page https://screenshots.firefox.com/1yMC3HD0LPpdThDQ/diveintohtml5.info and looks like it is in a broken state.

Not sure how I can fix it though. So reporting if you are not aware.

Thank you.

**Comment by jonathantneal** [comment]
I just loaded the page in Firefox 57 and it looks great. Could you tell me more about how you are looking at the page? Which version of Firefox? Perhaps you have webfonts disabled?

**Comment by harikt** [comment]
I am also using Firefox 57 ( 64 bit ) on Ubuntu. 

I have not disabled anything. Also I am not sure how to disable webfonts in Firefox. But as you can see in screenshot the contents are not loaded.

**Comment by harikt** [comment]
Its loading now as expected. Not sure what happened before. Tested again with Firefox and Chrome after a restart.
