### ISSUE TITLE
Please provide an HTTPS website link

### ISSUE THREAD

**Issue by ghost** [diveintomark/diveintohtml5#92]
Thanks in advance from a friend from Fluent 2012.

**Comment by paulirish** [comment]
tbh i'm not sure where this site is still being served. the http://diveintohtml5.info/ link gives me "access denied".. then http://diveinto.html5doctor.com/ seemingly works, but the content appears to be old.

it's been a while.. hmm.

see also #83 as i think the domain reg is in a weird state.

**Comment by jonathantneal** [comment]
Yes, my server got owned once and I’ve had to manually restore each site. I’ll start that process now.

**Comment by jonathantneal** [comment]
I’ve fixed it, pulled the latest changes, and requested an SSL certificate for https://diveintohtml5.info/

**Comment by paulirish** [comment]
@jonathantneal i'm seeing the HTTPS working here.

want to set up a redirect?

**Comment by jonathantneal** [comment]
@paulirish, if I understood correctly; http is now redirecting to https. ⭐️

**Comment by paulirish** [comment]
yup! looks good. thx man!
